openapi: '3.1.0'
info:
  title: MyRecallAppService
  version: 1.0.0
servers:
  - url: http://0.0.0.0:8081/api
    description: Network deployment
paths:
  /pjson:
    get:
      operationId: putJson
      parameters:
      - name: user
        required: false
        in: query
        description: The owner of the topic.
        schema:
          type: string
      - name: topic
        required: false
        in: query
        description: The topic name.
        schema:
          type: string
      - name: content
        required: false
        in: query
        description: The JSON content of the topic.
        schema:
          type: string
      responses:
        '200':
          description: A success response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Json'
components:
  schemas:
    Json:
      type: object
      properties:
        message:
          type: string
      required:
        - message
